[tool.black]
line-length = 120
target-version = ['py310']

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.pytest.ini_options]
addopts = "-ra --cov --cov-fail-under=100"
